### ISSUE TITLE
Assignment 2 Update: Day 2

### ISSUE THREAD

**Issue by yashodha8** [mapschool/cartography#15] opened 2016-02-18 08:37 UTC
For #12

**Comment by prajography** [comment] 2016-02-18 12:23
Arun is there any way that I can get the boundaries of all the towns in Sindhudurg district through Overpass.turbo or any other way.

**Comment by tantadang** [comment] 2016-02-18 12:32
![fort-kochi-tourism-map-v2 0](https://cloud.githubusercontent.com/assets/16536337/13143353/4509fdc8-d669-11e5-90ff-efb81f77f478.jpg)

### Fort Cochin Tourism Map V2.0

CHANGELOG
- Added Places of Religious Interest with their respective symbols. 
- Changed colors of road as suggested. 
- Main road and street roads in different shades. 
- Added Ferry Terminal Icon

**Comment by planemad** [comment] 2016-02-18 18:02
@prajography you will need to trace town boundaries in OSM first, I dont think they are already available. What you can get is point data for location of town, village, hamlet. Just search in Overpass for `place=town` or just `place`

**Comment by planemad** [comment] 2016-02-18 18:08
@tantadang  theme looks supercool :cool: a pattern usually followed for markers is to use a marker color to represent a broad category, like eateries, sacred places, transport, tourism etc, and use the icon to differentiate the sub category like cafe, pub, restaurant etc. This make the marker much easier to scan for the eye, first by color, and then looking at the icon details.

**Comment by arshedhakeem** [comment] 2016-02-18 18:14
![1](https://cloud.githubusercontent.com/assets/16536380/13153133/7e4a9280-d698-11e5-8250-845d2d577aaf.png)

> Ayurvedic pharmacies/dispensaries to be added
> data for classification in-terms of treatment to be figured out

ISSUE: Not able to upload the below CSV file into mapbox. Cudn't figure out the cause
[AYURVEDIC Resorts_2.zip](https://github.com/mapschool/course/files/136690/AYURVEDIC.Resorts_2.zip)

**Comment by prajography** [comment] 2016-02-18 18:29
![sindhudurg map_r3_1](https://cloud.githubusercontent.com/assets/16536383/13153686/4f729946-d69b-11e5-8b30-3ba9bfd57ae0.jpg)
![sindhudurg map_r3_2](https://cloud.githubusercontent.com/assets/16536383/13153689/53abef94-d69b-11e5-8fde-6b939390e073.jpg)
![sindhudurg map_r3_3](https://cloud.githubusercontent.com/assets/16536383/13153691/569ae5de-d69b-11e5-98d1-6a76362bb4c7.jpg)

Changed the color palette of Map.
Added the icons and names of places which will vary in sizes according to zoom level.

Icons of 3 more categories yet to be added.

**Comment by planemad** [comment] 2016-02-18 18:34
@arshedhakeem  looks like an issue in our upload system and have logged an issue. This should be solved by morning or in a few hours. Thanks for reporting this.

@prajography Wow colors :heart_eyes: looks like aged paper.

**Comment by tinozza** [comment] 2016-02-18 20:04
# Trekking Map

![1](https://cloud.githubusercontent.com/assets/16536421/13156149/1553878c-d6a7-11e5-9179-4cd94d5ea0ce.JPG)

With the trekking spots according to the degree of difficulty

![image](https://cloud.githubusercontent.com/assets/16536421/13156391/4471f804-d6a8-11e5-93f6-36b257c14654.png)
Labels of the major townships on zooming in

![2](https://cloud.githubusercontent.com/assets/16536421/13156151/16704858-d6a7-11e5-80b3-b8b901d0049e.JPG)
Trying to get the specific routes from Bangalore to the Trekking spot highlighted

### Yet to add:

Filters by Location type - Waterfalls, Pilgrimage etc., onsite camping, distance from Bangalore etc.

Issues:
Can the path be added as gpx by mapping them individually through google maps?

**Comment by planemad** [comment] 2016-02-19 03:22
@arshedhakeem upload should be fixed now.

**Comment by arshedhakeem** [comment] 2016-02-19 06:49
@planemad  I tried uploading the same CSV and its showing the below highlighted error now

I had uploaded a CSV earlier and it successfully uploaded, but had excluded the (lat,long) details of some places. I then tried putting these excluded places into a new CSV and tried uploading. The following error is pertaining to that new CSV.

![screenshot 64](https://cloud.githubusercontent.com/assets/16536380/13168412/8128a1e4-d702-11e5-9971-fad14b791807.png)

**Comment by planemad** [comment] 2016-02-19 07:34
@tinozza this is coming out really well.The zoomed out view looks really detailed, but without labels its hard to get context of the places. Maybe you can also add what might be zones with clusters of trekking spots, one would be Western Ghats, one would be Bangalore-Mysore. Each of the zones has a very different overall experience.

**Comment by planemad** [comment] 2016-02-19 10:41
tracking on #16

**Closed as completed by planemad** 2016-02-19 10:41 UTC
Labels: NID-BLR-2016

**Comment by planemad** [comment] 2016-02-19 10:42
@tinozza regarding the tracks, yes, you can trace them in Gmap and export it as a KML which can be imported in Studio. Alternatively you can also do this with http://geojson.io and upload it as a geojson.
