### ISSUE TITLE
Geo Viz & Cartography Inspiration & Critique

### ISSUE THREAD

**Issue by rasagy** [mapschool/cartography#71] opened 2023-01-30 07:10 UTC
Everyone picks two examples, one each of a map (or cartography piece) and a geo-visualization (map with lot of data overlaid).

For the map, write about:
- link to the map
- the designer/cartographer
- the topic/area the map represents
- the style of map
- what you loved
- what could be better

For the geoviz:
- link to geoviz
- topic of visualization
- creator/designer
- the data that is being visualized
- the data visualization technique that is being used
- the visual encoding that is being used
- what did you learn from this geoviz
- what you loved
- what could better

### References
* Maarten’s [List of Data Visualization Lists](https://www.maartenlambrechts.com/2023/01/02/the-list-of-2022-visualization-lists.html) (also see [2021](https://www.maartenlambrechts.com/2021/12/29/the-list-of-2021-visualization-lists.html))
* [David Rumsey’s Cartography Archive](https://www.davidrumsey.com/view)
* Rasagy’s [Map Board on Pinterest](https://in.pinterest.com/rasagy/for-the-love-of-maps/)

**Comment by Rajeshm006** [comment] 2023-01-30 08:40
Cartography piece:
### Al-Idrisi Mediterranean Map

![image](https://user-images.githubusercontent.com/111482817/215431237-4b9bd737-ed8c-47fe-b75f-c21fa5ace1e4.png)




Link: https://education.nationalgeographic.org/resource/al-idrisi

Designer/cartographer: Abū Abdallāh Muhammad ibn Muhammad ibn Abdallāh ibn Idrīs al-sharif al-Idrīsī, or simply **al-Idrisi.**

The topic/area the map represents: This al-Idrisi map contains the Mediterranean Sea, northern Africa, Europe, and parts of Asia.

What you loved: The route and branching are visible. To an extent, I can see the terrain also.

What could be better: Visual Encoding of Data, the mountains, or the color-coded mountain-like elements doesn't convey the meaning of what it is depicting.

Geoviz:
### Power Centers of the Fortune 500

![image](https://user-images.githubusercontent.com/111482817/215656754-628f20b7-2cc0-4c1f-af23-cf1964e5e53e.png)

Link: https://nicolasrapp.com/studio/portfolio/power-centers-of-the-fortune-500/

Creator/Designer: Nicolas Rapp Design Studio

The data that is being visualized:  each dot represents a metropolitan area with at least one fortune 500 company
The data visualization technique that is being used: Dots
The visual encoding that is being used: Dots
what did you learn from this viz:  The map is a skewed little bottle in the top to get the spherical effect, which adds depth of field
what you loved: One layer of data spread across the map without any clutter
what could be better: The No. of Companies also can be encoded, the size of the dot might clash with other places, might be saturation of one hue could have helped

**Comment by 8PocketElf** [comment] 2023-01-30 09:02
https://www.reddit.com/r/MapPorn/comments/yqzgkv/land_doesnt_vote_people_do/

link to geoviz
topic of visualization - land area vs population of each contituency
creator/designer - karim douieb
the data that is being visualized - land area vs population of each contituency
the data visualization technique that is being used - cartogram
the visual encoding that is being used - color and shape
what did you learn from this geoviz - 
what you loved - the way states shape transformed into the population to show the real impact
what could better

<img width="897" alt="Screenshot 2023-01-30 at 2 35 27 PM" src="https://user-images.githubusercontent.com/111482797/215433487-a3f7d691-e3e6-468a-bad1-874d2aecd161.png">

<img width="897" alt="Screenshot 2023-01-30 at 2 34 58 PM" src="https://user-images.githubusercontent.com/111482797/215433379-431e71f1-140e-49f0-857e-402dfa88c1a6.png">


https://www.reddit.com/r/ShitAmericansSay/comments/10oj5iy/this_map_published_in_1942_by_an_american_of_a/

https://en.m.wikipedia.org/wiki/Outline_of_the_Post-War_New_World_Map

link to the map
the designer/cartographer
the topic/area the map represents
the style of map
what you loved
what could be better

![image](https://user-images.githubusercontent.com/111482797/215671777-979fb128-35ee-41e0-86ac-a406862e6837.png)

**Comment by mohnishlandge** [comment] 2023-01-30 09:06
### 1. Map

C1871
Sud-Polar Karte
A.H. Petermann (1822 - 1898)
Very detailed German map.

![image](https://user-images.githubusercontent.com/60274031/215673328-633e4eff-5293-4037-a264-ca8bb43e1854.jpeg)

### 2. Geoviz

- link to geoviz : https://realitycheck.wordpress.com/2006/11/01/the-india-social-cartogram-project-maps/
- topic of visualization : Carto
- creator/designer: realitycheck 
- the data that is being visualized : India's Population, area, and Different Cast data
- the data visualization technique that is being used : Cartograms
- the visual encoding that is being used : Size
- what did you learn from this geoviz
- what you loved : I like the correlation of different categories in this geoviz. This perspective is not really noted in day to day life. 
- what could better

![Geospatial-7](https://user-images.githubusercontent.com/60274031/215432033-f1e59f35-3713-44f4-a831-1e5b437d7408.png)

**Comment by amandeep2496** [comment] 2023-01-30 21:39
[Atlas Blaeu Van Der Hem](https://maps.nls.uk/view/103831293)
Designer: [Van Der Hem](https://en.wikipedia.org/wiki/Laurens_van_der_Hem)
![image](https://user-images.githubusercontent.com/90832949/215660138-b4e28647-1d8a-4cf3-8983-baa9bfe99d7e.png)

**Topic:** Representing the entire surface of the Earth, the 50-volume Atlas Blaeu-Van der Hem atlas contains more than 2,400 maps, prints, and drawings and offers a pictorial encyclopedia of 17th century knowledge ranging from geography and topography to warfare and politics.
**Importance:** First maps to portray the earth flat on two circles.




![image](https://user-images.githubusercontent.com/90832949/215601206-a2dc7d10-1526-4011-a690-b3bbcb9d6eb5.png)
![image](https://user-images.githubusercontent.com/90832949/215601362-3ceb8ddd-f0bc-4539-9e21-fd659544fe9d.png)

### For the Geoviz:

- Link to geoviz: [Mapping Iran's Unrest](https://www.theguardian.com/world/ng-interactive/2022/oct/31/mapping-irans-unrest-how-mahsa-aminis-death-led-to-nationwide-protests) 
- Topic of Visualization: **Mapping Iran’s unrest: how Mahsa Amini’s death led to nationwide protests**
- Creator/Designer: [Niels de Hoog](https://www.theguardian.com/profile/niels-de-hoog) and [Elena Morresi](https://www.theguardian.com/profile/elena-morresi)
- The data that visualised: **How Mahsa Amini’s death led to nationwide protests**
- Visualization technique that is being used: **Dots**
- The visual encoding that is being used: **Dots representing civil protests**
- What did you learn this geoviz: **How a map with simple timeline and a crucial topic can produce a strong narrative.**
- What you loved: **How the geoviz shows the progression of the protests from a localised area (zoomed in) to nationwide protests spurting up in different parts of the country**
- What could better: **Maybe representing how the idea of these protests spreading was also shown in some way on the map. Basically, right now looking at the final map it seems that the protests were disjointed.**

**Comment by karthikeya-gs07** [comment] 2023-01-31 01:02
## [Map: First Printed Map of Asia](https://mappingbengal.com/first-map-of-asia)
Map By - Sebastian Munster

![7266300c-6ee5-4eb2-87a3-b74909327011_rw_1920](https://user-images.githubusercontent.com/39125026/215644672-f5862932-c78e-4cbd-96af-184c02522841.jpg)

### About
The first printed map of the Asian continent. First printed in 1540 CE, this map combines the information from Ptolemy and Marco Polo as well as the more recent expeditions of the Portuguese India Armadas and Ferdinand Magellan’s circumnavigation of the earth.

### Style of Map
Not Sure

### Likes & Potential Improvements
I like the fact that the entire map is a summative understanding of Asia through insights collected across various voyages. The simplicity of the map and the tube-like mountains that are partially accurate.

Do not find any potential improvements (not sure of what the cartographer knew and referred to make this map, could be the best outcome based on the then current knowledge)
___


## [GeoViz Map: North American Species Migration Map](https://education.nationalgeographic.org/resource/north-american-species-migration-map)
Map By - WILLIAM E. MCNULTY

![migration-routes](https://user-images.githubusercontent.com/39125026/215635304-c3dd9156-1d0e-4bb7-82d7-2bd0666c9246.jpg)

### Data Being Visualized
The map shows the migration routes of Sandhill Cranes, Pronghorns, Monarch Butterflies & Mexican Free-Tailed Bats over the period of a year. 

### Data Visualization Technique
It is a **terrain-based political map** which is superimposed with a **flow map** of the migratory animals.

### Visual Encoding
There are two levels of visual encoding.
**Arrows:** Depict the direction and span of migration distance.
**Colour:** Depict the species that are undergoing migration.
**Labels:** Indicating the major cities that fall in the path of migration.

### Learning

1. The Sandhill Cranes migrate the greatest distance among the species indicated on the visualisation. They migrate between Serbia and Mexico, travelling a distance of 5000+ miles.
2. Pronghorns have the shortest migration distances i.e. within America or between America & Cannada.
3. Monarch butterflies are the most divergent migrating species. They are mostly seen migrating on the west and east coast of America.
4. Mexican Free-Tailed Bats have a singular migration path and do not diverge like Monarchs.


### Likes & Potential Improvements
The map is a simple representation of the paths the species take for migration. It doesn't require any cognitive load to understand the map. It is interesting to see the mean map of the species across the countries which gives a great sense of the distance they cover.

The map could be made more informative by mentioning the time of migration and the population distribution across paths by encoding the width of the arrow as population size. The double-sided arrow leaves ambiguity on the time of movement.
___

**Comment by geetanjalikhanna98** [comment] 2023-01-31 02:36
**Cartography Piece:**

### Fra Mauro's Mappa Mundi (Map of the World), Circa 1450

![Fra Mauro Map](https://user-images.githubusercontent.com/36082594/215642678-123fee48-66db-4c5a-96a4-f5d5e132d41b.jpeg)

![Fra Mauro Map - 2](https://user-images.githubusercontent.com/36082594/215642953-ff6bb75d-7789-467c-bc60-1bce89397e97.png)

- **Link to the map:** [Fra Mauro's Mappa Mundi Google Arts and Culture](https://artsandculture.google.com/story/fra-mauro-s-mappa-mundi/8QXhzVkYn-sMLA?hl=en)

- **The designer/cartographer:** Fra Mauro was a Venetian cartographer who lived in the Republic of Venice. He created the most detailed and accurate map of the world up until that time, the Fra Mauro map. Mauro was a monk of the Camaldolese Monastery of St. Michael, located on the island of Murano in the Venetian Lagoon. It was there that he maintained a cartography workshop. Powerful men like Prince Henry the Navigator also employed him. In his youth, he traveled extensively as a merchant and a soldier which inspired his interests. The map was commissioned by King Afonso V of Portugal. Fra Mauro created it without leaving his monastery, assisted by Andrea Bianco, a sailor, and cartographer who was also from Italy. [More about the cartographer](https://www.atlasobscura.com/articles/fra-mauro-map)

- **The topic/area the map represents:** Despite the inversion, the map is exceptionally accurate compared with its predecessors. It includes detailed representations of largely unmapped areas of India, Africa, China, and Japan. He was also one of the first to suggest that the Indian Ocean was not closed and Africa could be circumnavigated by her southern end. It was created using crowdsourced data collected from expeditions carried out by Chinese and Arab sailors, traders, and voyagers across the Indian Ocean.

- **The style of the map:**  It is a circular planisphere drawn on parchment, oriented to the south, and mounted on a wooden stretcher frame around 6.5 feet (2 m) in diameter. It is an illustrative piece of cartography known for it's thoroughness and accuracy.

- **What I loved:** The geographical accuracy achieved in the time through crowdsourcing and the immense attention to detail with thousands of illustrations and annotations on the map, speaking not just of geography but unique stories and experiences of people in the lands studied.

---

**Geo Visualization:**

### Mapping where the earth will become uninhabitable
_Berliner Morgenpost_

![Geo Viz](https://user-images.githubusercontent.com/36082594/215650980-2f3217af-9f77-45b1-a473-dc5f267f0c36.png)

- **Link to Geo Viz:** [Climate Crisis: Mapping where the earth will become uninhabitable](https://interaktiv.morgenpost.de/klimawandel-hitze-meeresspiegel-wassermangel-stuerme-unbewohnbar/en.html)

- **Topic of visualization:** The geo-visualization focuses on how climate change is destroying people's livelihoods. It represents the areas that will become “uninhabitable” by the year 2100 due to factors like extreme heat, tropical cyclones, rising sea levels, water stress, or a combination of those are projected to make it difficult or impossible to live there.

- **Creator/designer:** [Ida Flik](https://idaflik.github.io/), [André Pätzold](https://www.twitter.com/alterpaetz) und [Benja Zehr](https://twitter.com/benjazehr).

- **Data that is being visualized:** [Raw Data:](https://docs.google.com/spreadsheets/d/1VUodfWICrEzc9q2doWKmaqZeXiq8e0c71yh1pgNN33M/edit)

The world map is divided into hexagons representing an area of around 12.000 square kilometers. For each area, the population is mapped to the height of the 3D hexagonal bin along with the present and predicted (2100) wet-bulb temperatures, the water stress levels, desert regions or heat waves, sea level rise, and tropical cyclones.

- **Data visualization technique that is being used:** Hexagonal Binning

- **Visual encoding used:**
- Position: Represents the geographical location of the area in the world
- Height(3D): Represents the current population size of inhabitants of the area
- Color: Represents the condition depicted including sea level rise, wet-bulb temperatures, etc.
- Opacity: Represents the extent of the condition in the given year to show how adversely affected or uninhabitable the area is at present and in the year 2100.

- **What did I learn from this viz:** 
- How 3D visualizations can be used effectively to communicate a message and retain readability
- Using interactivity to tell a story and generate interest in the message to be told

- **What I loved:** The use of interactivity to generate interest and contrast between the present and predicted scenario to highlight the alarming need for action.

- **What could be better:** Showing population as height led to an incorrect intuition on viewing the visualization that areas with larger height were in more alarming positions due to increased visual density of the hue used to show the adverse impacts. It took some adjustment of the mental model to perceive the graph as intended.

**Comment by ankita360** [comment] 2023-01-31 03:07
# 1.  Cartography Piece

![15211001](https://user-images.githubusercontent.com/123930284/215658402-4177cd46-ba34-400d-ae8c-733b61db1e04.jpg)
![15211003](https://user-images.githubusercontent.com/123930284/215669020-db5aae94-36d8-4ea2-b815-d6855249f77b.jpg)


*Link*: [_Crossings in the Oder river basin and the coastal rivers in Pomerania_](https://www.davidrumsey.com/luna/servlet/detail/RUMSEY~8~1~344573~90112547:Covers--%C3%9Cbersichtskarte-der-%C3%9Cberg%C3%A4n?sort=pub_list_no_initialsort%2Cpub_date%2Cpub_list_no%2Cseries_no)
_Also refer:_ [_Related_](https://www.davidrumsey.com/luna/servlet/detail/RUMSEY~8~1~344575~90112552:Teil-II-%C3%9Cbersichtskarte-der-%C3%9Cberg%C3%A4n?qvq=q:pub_list_no%3D%2215211.000%22;lc:RUMSEY~8~1&mi=2&trs=8#)

### Cartographer
This map was published by Reichsamt fur Landesaufnahme (Reich Office for State Recording), under Mil-Geo (The geographic service of the German army) in 1938.

### Intent of the map
This is an overview map of the crossings in the Oder river basin and the coastal rivers in Pomerania in 6 parts. It was prepared in the lead-up to the Invasion of Poland during World War II. There are several warnings written on the map regarding confidentiality that suggest that the planning of this invasion was an extremely sensitive issue.

### Style of the map
This is a cartometric map, detailing out river crossings and related infrastructure on the western Polish frontier with Germany.

### Critique
Considering that the goal of the map is to cover all necessary information for the logistical planning and execution of Germany's nascent blitzkrieg, it seems to do a great job at dividing and structuring information to make it possible to pin-point any location by plotting "zones" over the river basin. Since this is only 1 of the 6 maps, the story is incomplete to make too many judgements; however the record suggests that the maps elaborate over a dozen symbols for bridges (rail, small gauge rail, road bridges of different capacities, etc.), ferries and canal overpasses - making them quite rich and comprehensive.
Regarding room for improvement, perhaps the numbers used to indicate zones on several levels could have better readability and more distinction than just size difference, as it is hard to tell which number corresponds to which level of zone.

# 2.  Geoviz [Discard this]
_This graphic was picked for the critique because of interesting narrative of mapping time in space. It was discarded on the realization that this doesn't qualify for geoviz, as it doesn't comprise of data overlaid on a map. Please find the final geoviz critique below this._

![canvas](https://user-images.githubusercontent.com/123930284/215667742-c1d59c3e-3a9b-458e-ae0a-57578557ccf5.png)

*Link*: [_The Temple of Time_](https://www.davidrumsey.com/luna/servlet/detail/RUMSEY~8~1~315043~90083688:The-Temple-of-Time?sort=Pub_List_No_InitialSort%2CPub_Date%2CPub_List_No%2CSeries_No&qvq=q:emma%20willard;sort:Pub_List_No_InitialSort%2CPub_Date%2CPub_List_No%2CSeries_No;lc:RUMSEY~8~1&mi=5&trs=245#)

### Creator
Emma Willard

### Intent of the visualization
This visualization aims to put the course of time in perspective in multiple dimensions, exhibiting nations both ethnographically and chronologically (chronographically?), along with many of the most celebrated leaders of the world. Includes notes on lower panel.

-----
_Please consider the following the final Geoviz critique:_

# 2.  Geoviz

![14359251](https://user-images.githubusercontent.com/123930284/215670742-6697b8a4-d910-4a81-a3b7-45e1c1047158.jpg)

*Link*: [_United States exports and imports of commodities : 1967_](https://www.davidrumsey.com/luna/servlet/detail/RUMSEY~8~1~341496~90109644:United-States-exports-and-imports-o?sort=pub_list_no%2Cseries_no&qvq=q:US%20exports;sort:pub_list_no%2Cseries_no;lc:RUMSEY~8~1&mi=5&trs=23#)

### Creator
National Geographic Society, U.S. Census Bureau 

### Intent of the visualization
This is a world map featuring United States exports and imports of commodities in 1967. It shows streams of commerce between the United States and other nations, national borders, bodies of water, drainage, glaciers, coastlines and islands.

### Data visualization technique being used
Flow Map + Piecharts

### Visual Encoding
1. Position: Geographical location
2. Magnitude and direction of exports and imports: Flow lines, arrows, piecharts
3. Types of commodities being exported and imported: Colour

### Critique
The visualization seems to do a decent job at communicating the intent, and is quite layered in terms of information conveyed. The thickness of flow lines helps to draw a clear picture of the amount of exports/imports happening.
Perhaps one thing that could be improved upon is the way that the top left and top right have boxes showing a summary of total exports and total imports, as they wrongly appear to be the legend for the piecharts at the first glance.

**Comment by ParvathyRaju98** [comment] 2023-01-31 04:32
# Cartography Map
## [Theatrum Orbis Terrarum](https://en.wikipedia.org/wiki/Theatrum_Orbis_Terrarum)

![OrteliusWorldMap1570](https://user-images.githubusercontent.com/111482857/215658137-f701696a-e554-4559-9e44-3560cb75d5b8.jpg)

### About
**Theatre of the Orb of the World** is considered to be the first true modern atlas released in 1570. It consisted of a collection of uniform map sheets and supporting text bound to form a book for which copper printing plates were specifically engraved. It's the first ever documented world map and was a compilation of 53 bundled maps of other masters and never virtually made from the hand of Ortelius

### Cartographer
**Abraham Ortelius** also Ortels, Orthellius, Wortels 94 or 14 April 1527 – 28 June 1598) was a Brabantian cartographer(, geographer and cosmographer. He is recognized as the creator of the first modern atlas, the Theatrum Orbis Terrarum (Theatre of the World). Along with Gemma Frisius and Gerardus Mercator, Ortelius is generally considered one of the founders of the Netherlandish school of cartography and geography. He was a notable figure of this school in its golden age (approximately 1570s–1670s) and an essential geographer of Spain during the period of discovery. The publication of his atlas in 1570 is often considered the official beginning of the Golden Age of Netherlandish cartography. He was the first person to propose that the continents were joined before drifting to their present positions

### Area Represented
This is the earliest rendition of Western European Knowledge of the **Entire World Map**

### Style of Map
The Latin stylization of Netherlandish Cartography is followed by using Serif Font Styles and Water Coloured Illustrations 

### What I loved
<img width="676" alt="Screenshot 2023-01-31 at 9 49 15 AM" src="https://user-images.githubusercontent.com/111482857/215662070-4f887297-00e1-4173-a017-52ea1e540345.png">
The interesting practice is that mapmakers would often place monsters and other imagined creatures in marked unexplored areas, like those seen in Ortelius's 1570 Theatrum Orbis Terrarum map. It was an indication that it could possibly be dangerous and one should only sail at their risk and is said to alert sailors and Voyagers.

It was also commendable that he outsourced and got maps from several cartographers than just making a map based on his personal knowledge

___

# Geo Visualization Map
## [After Babylon](http://www.puffpuffproject.com/languages.html)
<img width="1072" alt="Screenshot 2023-01-31 at 10 42 47 AM" src="https://user-images.githubusercontent.com/111482857/215671360-da55114c-d121-4e9c-841c-db3ffac7eb8d.png">

### Topic of Visualization
This visualisation is the current linguistic condition of the world. This map is a data visualisation of the languages spoken in the world and also studies where the origin of the language was and how it has migrated and spread across the world. The correlational migration of language.

### Creator
Puff Puff Project Student Team ( Milan, Italy )

### Data Being visualised
Language is the method of human communication, either spoken or written, consisting of the use of words in a structured and conventional way. This visualisation is the current linguistic condition of the world. To understand how languages have developed and transcended beyond borders and how the Language Loanward Mapping is like. a loanword is a word adopted from another language and completely or partially naturalised.

### Data Viz Technique
Dot Charting and Flow Mapping

### Data Encoding
- Usage of colours to differentiate the most spoken languages
- White dots are used to represent the birthplace of the language
- The size of the dot depicts the volume of the speakers of that particular language
- Labels to denote the languages

### What I learnt
How such dense information can be presented in a concise way and the interactive feature helps visualise the separate linguistic relationship between two languages

**Comment by kowsie** [comment] 2023-01-31 05:02
**Geo visualization**
![image](https://user-images.githubusercontent.com/111482788/215667352-ddc89726-0b8a-4c39-914e-16deaff6a73f.png)

**link to geoviz:** https://cargocollective.com/federicafragapane/The-Analytical-Map-of-Piedmont
**topic of visualization:** The Analytical Tourism Map of Piedmont
**creator/designer:** Marco Bernardi ,Federica Fragapane, Francesco Majno
**the data that is being visualized:** The Analytical Tourism Map of Piedmont has been realized analyzing and investigating the issue in complete and detailed way, considering both the attraction factors of the region and the evolution and dimension of tourists flows and accommodations. 
On the left part of the poster, the Piedmont's map shows the most important landscape assets, architectural heritage buildings and museums, winter sports facilities, gastronomic products and wine. Every element is geolocated on the map, and it's easy to identify the beauties of different territories and the best places to visit.
On the right side, the visualization shows the variations of tourist flows (from 2006 to 2012) compared with the accommodations (hotels, bed and breakfasts, hostels, campgrounds, etc.), all divided in the 8 provinces of Piedmont.
the data visualization technique that is being used: 
**the visual encoding that is being used:**
Icons representing architectural heritage
Colored circles representing Museums
Patterns representing parks
Size represents tourist flows and accommodation
**what did you learn from this geoviz**
the visualization shows the variations of tourist flows (from 2006 to 2012) compared with the accommodations (hotels, bed and breakfasts, hostels, campgrounds, etc.), all divided in the 8 provinces of Piedmont. It clearly stands out how hotels hosts the greatest amount of people, but also how the number of B&B and Agritourism's is strongly increasing in the last years.
**what you loved**
Every element is geolocated on the map, and it's easy to identify the beauties of different territories and the best places to visit.
The segregation of data on the left part of the poster, the Piedmont's map showing the most important landscape assets through icons and On the right side, the visualization showing the variations of tourist flows through sizes overall allows to add more details and gives more clarity.

**Comment by speckx** [comment] 2023-01-31 05:44
**Meghana** 

**Map** 
Old, antique bird's eye view and plan of the isle and city of Goa, by Jan Huygen van Linschoten
![AMH-6577-KB_Bird's_eye_view_of_the_city_of_Goa](https://user-images.githubusercontent.com/111493088/215671749-0c0c97de-0e41-48e6-a431-edd151a273e1.jpg)

**Cartographer**
Jan Huygen van Linschoten (1562-1611)

**What it represents**
Map and landscape of Goa while a peculiar emphasise on sea trade route and canals


**Map Style**
Hand engraved illustration. A combination of plan and bird's eye view.

**what I loved**
The map shows essence of Van Linschoten’s travel account, supplemented by further information on the peoples, flora, and fauna of the Asian territories.


**Geo Viz - Guide for visitors to Ise Shrine, Japan c.1950**
![MapCarte32_ise_large (1)](https://user-images.githubusercontent.com/111493088/215674408-0eeda144-483c-41ca-8b6c-bba61d433e8e.png)


**What it represents**
The rail route of Ise Shrine

**Map Style**
A schematic map combined with isometric map


**what I loved**
A good example of letting the map itself influence the overall design rather than constraining it to standard formats.

The painting has less content as it approaches the right edge before it becomes schematic to support the transition and the upright orientation of the typography works well with other vertical map elements.

**Closed as completed** 2023-08-10 05:53 UTC
Labels: NID-BLR-2023
